-- 버전 1: UNION 방식으로 0~23 시간 생성
SELECT hours.HOUR, COALESCE(counts.COUNT, 0) AS COUNT
FROM (
    SELECT 0 AS HOUR UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION
    SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION
    SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION
    SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION
    SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION
    SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23
) AS hours
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) AS counts ON hours.HOUR = counts.HOUR
ORDER BY hours.HOUR;

-- 버전 2: WITH RECURSIVE 방식으로 0~23 시간 생성
WITH RECURSIVE hours AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM hours WHERE HOUR < 23
)
SELECT h.HOUR, COALESCE(COUNT(a.DATETIME), 0) AS COUNT
FROM hours h
LEFT JOIN ANIMAL_OUTS a ON h.HOUR = HOUR(a.DATETIME)
GROUP BY h.HOUR
ORDER BY h.HOUR;

-- 혼자 구현한 코드 (입양 기록이 있는 시간대만 조회)
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
ORDER BY HOUR