SELECT 
    ID, FISH_NAME, LENGTH
FROM 
    FISH_NAME_INFO AS NAME
INNER JOIN 
    (SELECT ID, FISH_TYPE, LENGTH
    FROM FISH_INFO
    WHERE (FISH_TYPE, LENGTH) IN
        (SELECT 
            FISH_TYPE, MAX(LENGTH) AS LENGTH
        FROM 
            FISH_INFO AS SUB
        GROUP BY FISH_TYPE)) AS INFO
ON NAME.FISH_TYPE = INFO.FISH_TYPE
ORDER BY ID ASC